# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tendies < Formula
  desc "Realized Schwab P&L CLI"
  homepage "https://github.com/batjaa/tendies"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/batjaa/tendies/releases/download/v0.4.1/tendies_0.4.1_darwin_amd64.tar.gz"
      sha256 "42f6d957e8121a1b2d82c8d475f575533a5d6708509f6a750d0fcb87dae5d1f7"

      define_method(:install) do
        bin.install "tendies"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/batjaa/tendies/releases/download/v0.4.1/tendies_0.4.1_darwin_arm64.tar.gz"
      sha256 "dd64a4b876d386bfeabb211fdb72ab575caf046e568ad718bf96a269e35d053e"

      define_method(:install) do
        bin.install "tendies"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/batjaa/tendies/releases/download/v0.4.1/tendies_0.4.1_linux_amd64.tar.gz"
      sha256 "461fdcdc0efd1cad91641c272a9f50717d9d2018692fe7b04257ac8444c5715d"
      define_method(:install) do
        bin.install "tendies"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batjaa/tendies/releases/download/v0.4.1/tendies_0.4.1_linux_arm64.tar.gz"
      sha256 "8798af9e396cdfa0ef41b1c556ad9cf3f791275a4615ad2f34883662513b6170"
      define_method(:install) do
        bin.install "tendies"
      end
    end
  end

  test do
    output = shell_output("#{bin}/tendies --help")
    assert_match "realized", output.downcase
  end
end
