# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tendies < Formula
  desc "Realized Schwab P&L CLI"
  homepage "https://github.com/batjaa/tendies"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/batjaa/tendies/releases/download/v0.3.0/tendies_0.3.0_darwin_amd64.tar.gz"
      sha256 "6635fb781068ee8fdbad7e39d3d88aa01709234316aa99168b0214c24165ee03"

      define_method(:install) do
        bin.install "tendies"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/batjaa/tendies/releases/download/v0.3.0/tendies_0.3.0_darwin_arm64.tar.gz"
      sha256 "fccc541affa2c05e1648d7feaadfc5b1f797db233864fa7e7d8686a71a1a1de6"

      define_method(:install) do
        bin.install "tendies"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/batjaa/tendies/releases/download/v0.3.0/tendies_0.3.0_linux_amd64.tar.gz"
      sha256 "c29cadae214645f7b3e9a6f16e392db861084a05010102f9be58987bf979b945"
      define_method(:install) do
        bin.install "tendies"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batjaa/tendies/releases/download/v0.3.0/tendies_0.3.0_linux_arm64.tar.gz"
      sha256 "07ebb13b3972c2224ef3ddd678ded94c071b29de3aa315b56a4bf3ba8b6f0d85"
      define_method(:install) do
        bin.install "tendies"
      end
    end
  end

  test do
    output = shell_output("#{bin}/tendies --help")
    assert_match "realized", output.downcase
  end
end
